### ISSUE TITLE
Remove empty build section in meta.yaml

### ISSUE THREAD

**Issue by bobleesj** [Billingegroup/staged-recipes-cookiecutter#16]
As discussed here: https://github.com/Billingegroup/staged-recipes-cookiecutter/issues/13#issuecomment-2327322865

The latest cookiecutter version renders into:

```
requirements:
  build:

  host:
    - python >=3.10
    - setuptools
    - pip

  run:
    - python >=3.10
    - numpy
```

For projects that do not require dependencies under `build `, we could simply remove the `build: ...` section so that we can save the conda-recipe reviewer's and our time.

```
requirements:
  host:
    - python >=3.10
    - setuptools
    - pip

  run:
    - python >=3.10
    - numpy
```
